-- 코드를 입력하세요
SELECT T.CAR_ID, T.CAR_TYPE,
    FLOOR(T.DAILY_FEE * ((100 - COALESCE(C.DISCOUNT_RATE, 0)) / 100) * 30) AS FEE
FROM (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('SUV', '세단')
    AND CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01' )
    ) AS T
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
    ON T.CAR_TYPE = C.CAR_TYPE AND C.DURATION_TYPE = '30일 이상'
    WHERE FLOOR(T.DAILY_FEE * ((100 - COALESCE(C.DISCOUNT_RATE, 0)) / 100) * 30) >= 500000
    AND FLOOR(T.DAILY_FEE * ((100 - COALESCE(C.DISCOUNT_RATE, 0)) / 100) * 30) < 2000000
ORDER BY FEE DESC, T.CAR_TYPE, T.CAR_ID DESC