SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO A
WHERE FAVORITES = (SELECT MAX(FAVORITES)
                   FROM REST_INFO B
                   WHERE B.FOOD_TYPE = A.FOOD_TYPE)
ORDER BY FOOD_TYPE DESC