SELECT a.HISTORY_ID,
   FLOOR(a.DAILY_FEE * ((100 - COALESCE(C.DISCOUNT_RATE, 0)) / 100) * (DATEDIFF(a.END_DATE, a.START_DATE) + 1)) AS FEE
FROM (
    SELECT  A.HISTORY_ID,
        A.START_DATE,
        A.END_DATE,
        B.CAR_ID,
        B.CAR_TYPE,
        B.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
    JOIN CAR_RENTAL_COMPANY_CAR AS B
    ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = '트럭') a
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON a.CAR_TYPE = C.CAR_TYPE
AND (
    CASE
        WHEN DATEDIFF(a.END_DATE, a.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(a.END_DATE, a.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(a.END_DATE, a.START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE '-'
        END
     ) = C.DURATION_TYPE
ORDER BY FEE DESC, a.HISTORY_ID DESC