SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY 
FROM ITEM_TREE AS T
JOIN ITEM_INFO AS I ON T.PARENT_ITEM_ID = I.ITEM_ID
JOIN ITEM_INFO AS C ON T.ITEM_ID = C.ITEM_ID
WHERE I.RARITY = 'RARE'
ORDER BY ITEM_ID DESC



