SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = (
    SELECT MAX(A2.LENGTH)
    FROM FISH_INFO AS A2
    WHERE A2.FISH_TYPE = B.FISH_TYPE
    )
ORDER BY A.ID
