SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS A
WHERE PRICE = ( SELECT MAX(PRICE)
                FROM FOOD_PRODUCT AS B
                WHERE A.CATEGORY = B.CATEGORY
                GROUP BY CATEGORY
                HAVING CATEGORY IN ('과자', '국', '김치', '식용유'))
ORDER BY MAX_PRICE DESC